routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('user.login.show');
Route::post('/login', 'Auth\LoginController@login')->name('user.login');

Route::group(['middleware' => 'auth'], function(){
});
*/
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.show');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::get('/admin/logout', 'Auth\AdminLoginController@logout')->name('admin.login.logout');

Route::get('/admin/types', 'TypeController@index')->name('admin.types.index');
Route::get('/admin/types/create', 'TypeController@create')->name('admin.types.create');
Route::post('/admin/types', 'TypeController@store')->name('admin.types.store');
Route::get('/admin/types/{id}/edit', 'TypeController@edit')->name('admin.types.edit');
Route::patch('/admin/types/{id}', 'TypeController@update')->name('admin.types.update');
Route::delete('/admin/types/{id}', 'TypeController@delete')->name('admin.types.delete');

Route::get('/admin/stations', 'StationController@index')->name('admin.stations.index');
Route::get('/admin/stations/create', 'StationController@create')->name('admin.stations.create');
Route::post('/admin/stations', 'StationController@store')->name('admin.stations.store');
Route::get('/admin/stations/{id}/edit', 'StationController@edit')->name('admin.stations.edit');
Route::patch('/admin/stations/{id}', 'StationController@update')->name('admin.stations.update');
Route::delete('/admin/stations/{id}', 'StationController@delete')->name('admin.stations.delete');

Route::get('/admin/trains', 'TrainController@index')->name('admin.trains.index');
Route::get('/admin/trains/create', 'TrainController@create')->name('admin.trains.create');
Route::post('/admin/trains/create/setStation', 'TrainController@setStation')->name('admin.trains.setStation');
Route::get('/admin/trains/create/route/{startStationEngName}/{endStationEngName}', 'TrainController@route')->name('admin.trains.route');
//Route::match(['get', 'post'], '/admin/trains/create/route', 'TrainController@route')->name('admin.trains.route');
Route::post('/admin/trains/create', 'TrainController@store')->name('admin.trains.store');
Route::get('/admin/trains/{train_number}/edit/info', 'TrainController@editInfo')->name('admin.trains.edit.info');
Route::patch('/admin/trains/{train_number}/edit/info', 'TrainController@updateInfo')->name('admin.trains.update.info');
Route::get('/admin/trains/{train_number}/edit/station', 'TrainController@editStation')->name('admin.trains.edit.station');
Route::post('/admin/trains/{train_number}/updateStation', 'TrainController@updateStation')->name('admin.trains.update.station');
Route::get('/admin/trains/{train_number}/edit/route/{startStationEngName}/{endStationEngName}', 'TrainController@editRoute')->name('admin.trains.edit.route');
Route::patch('/admin/trains/{train_number}/edit/route', 'TrainController@updateRoute')->name('admin.trains.update.route');
Route::delete('/admin/trains/{train_number}', 'TrainController@delete')->name('admin.trains.delete');

//Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/trains', 'TrainController@userIndex')->name('user.trains.index');
Route::get('/trains/{train_number}', 'TrainController@show')->where('train_number', '[0-9]+')->name('user.trains.show');
Route::get('/trains/search', 'TrainController@searchByNumber')->name('user.trains.search.by.number');
Route::post('/trains', 'TrainController@NumberSearchResult')->name('user.trains.number.search.result');
Route::get('/', 'TrainController@searchTrain')->name('user.trains.search');
Route::get('/trains/result/{boardingDate}/{startStationEngName}/{endStationEngName}/{type_id}', 'TrainController@TrainSearchResult')->name('user.trains.search.result');
//Route::match(['get', 'post'], '/tickets/create', 'TicketController')->name('tickets.create');

Route::get('/tickets', 'TicketController@index')->name('user.tickets.index');
//Route::get('/tickets/create', 'TicketController@create')->name('user.tickets.create');
Route::match(['get', 'post'], '/tickets/create', 'TicketController@create')->name('user.tickets.create');
Route::post('/tickets', 'TicketController@store')->name('user.tickets.store');
Route::get('/tickets/search', 'TicketController@search')->name('user.tickets.search');
Route::get('/tickets/{ticketNumber}', 'TicketController@show')->name('user.tickets.show');
Route::post('/tickets/search/result', 'TicketController@searchResult')->name('user.tickets.search.result');
Route::delete('/tickets/cancel/{ticketNumber}', 'TicketController@cancel')->name('user.tickets.cancel');

Route::get('/admin/tickets/search', 'TicketController@adminSearch')->name('admin.tickets.search');
Route::post('/admin/tickets/search/result', 'TicketController@adminSearchResult')->name('admin.tickets.search.result');
Route::delete('/admin/tickets/cancel/{ticketNumber}', 'TicketController@adminCancel')->name('admin.tickets.cancel');

app/DrivingWeek.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DrivingWeek extends Model
{
    public $timestamps = false;
    protected $table = 'driving_weeks';
    //建立關聯
    //行駛的列車
    function train(){
    	return $this->hasOne('App\Train', 'id', 'train_id');
    }

    //accessor
    public function getChineseNameAttribute(){
    	$arr_chineseNames = ['一', '二', '三', '四', '五', '六', '日'];
    	$index = $this->week - 1;
    	return $arr_chineseNames[$index];
    }
}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    //啟程車站
    function start_station(){
    	return $this->hasOne('App\Station', 'id', 'start_station_id');
    }

    //終點車站
    function end_station(){
    	return $this->hasOne('App\Station', 'id', 'end_station_id');
    }

    //訂購的列車
    function train(){
    	return $this->hasOne('App\Train', 'number', 'train_number');
    }

    //accessor
    //定義時間欄位的顯示格式
    public function getCreatedAtAttribute($value)
    {
        return date('Y-m-d H:i', strtotime($value));
    }

    public function getCanceledAtAttribute($value)
    {
        return date('Y-m-d H:i', strtotime($value));
    }

    public function getDeletedAtAttribute($value)
    {
        return date('Y-m-d H:i', strtotime($value));
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Station;
use App\Train;
use App\DrivingWeek;
use App\Ticket;
use App\Route;
use DB;
use Session;
use Auth;

class TicketController extends Controller
{
	public function __construct()
	{
	    $this->middleware('auth:admin', ['only' => ['adminSearch', 'adminSearchResult', 'adminCancel']]);
	}

    public function index(){
    	return redirect()->route('user.tickets.create');
    }

    public function create(Request $request){
    	$stations = Station::get();
        $input = array();

        //從訂票按鈕過來
        if ($request->isMethod('post')) {
            $validator = Validator::make($request->only(['trainNumber', 'startStation', 'endStation']), [
                'trainNumber'=>'required|numeric|exists:trains,number',
                'startStation'=>'required|exists:stations,english_name|not_in:'.$request->endStation,
                'endStation'=>'required|exists:stations,english_name|not_in:'.$request->startStation
            ]);

            if(!$validator->fails()){
                $train = Train::where('number', $request->trainNumber)->first();
                $startStation = Station::where('english_name', $request->startStation)->first();
                $endStation = Station::where('english_name', $request->endStation)->first();

                //判斷列車是否有停靠起訖站
                $arr_routeInfomation = $train->getRouteInfomationAttribute();
                if( (array_key_exists($startStation->id, $arr_routeInfomation) && $arr_routeInfomation[$startStation->id]['departureTime'] > 0) && (array_key_exists($endStation->id, $arr_routeInfomation) && $arr_routeInfomation[$endStation->id]['departureTime'] > 0) ){
                    $input['trainNumber'] = $train->number;
                    $input['startStation'] = $request->startStation;
                    $input['endStation'] = $request->endStation;
                }
            }
        }

    	return view('user.tickets.create')->with(["stations" => $stations, "input" => $input]);
    }

    public function store(Request $request){
    	$rules = [
    		"cellPhoneNumber" => "required|regex:/(^09[0-9]{2}-[0-9]{6}$)/",
    		'startStation'=>'required|exists:stations,english_name|not_in:'.$request->endStation,
	        'endStation'=>'required|exists:stations,english_name|not_in:'.$request->startStation,
	        'boardingDate'=>'required|date_format:Y-m-d',
	        'trainNumber'=>'required|numeric|exists:trains,number',
	        'numberOfTickets'=>'required|numeric|between:1,100',
    	];
    	$this->validate($request, $rules);

    	//判斷搭乘日期
    	if(strtotime(date('Y-m-d', time())) > strtotime($request->boardingDate)){
    		return redirect()->route('user.tickets.create')
	    			->withErrors(['boardingDate'=>'請輸入有效的日期'])
	    			->withInput();
    	}

    	$train = Train::where('number', $request->trainNumber)->firstOrfail();
    	$startStation = Station::where('english_name', $request->startStation)->firstOrfail();
    	$endStation = Station::where('english_name', $request->endStation)->firstOrfail();

    	//判斷當日有無該車次的列車
    	//將日期轉換為星期
	    $arr_weekEngNames = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
	    $week = array_search(date("D",strtotime($request->boardingDate)), $arr_weekEngNames)+1;
	    if(DrivingWeek::where('train_id', $train->id)->where('week', $week)->count() <= 0){
	    	return redirect()->route('user.tickets.create')
	    			->withErrors(['boardingDate'=>'當日無該車次的列車'])
	    			->withInput();
	    }

    	//判斷該列車有無行經起訖站
    	if($train->start_station_id != $startStation->id){
    		if(Route::where('train_id', $train->id)->where('station_id', $startStation->id)->where('stay_time', '>', 0)->count() <= 0){
    			return redirect()->route('user.tickets.create')
	    			->withErrors(['startStation'=>'該列車無行經起訖站'])
	    			->withInput();
    		}
    	}

    	if($train->end_station_id != $endStation->id){
    		if(Route::where('train_id', $train->id)->where('station_id', $endStation->id)->where('stay_time', '>', 0)->count() <= 0){
    			return redirect()->route('user.tickets.create')
	    			->withErrors(['endStation'=>'該列車無行經起訖站'])
	    			->withInput();
    		}
    	}

    	//判斷發車時間是否已過
    	if(strtotime($request->boardingDate.' '.$train->route_infomation[$startStation->id]['departureTime']) < strtotime(date("Y-m-d H:i", time()))){
    		return redirect()->route('user.tickets.create')
	    			->withErrors(['trainNumber'=>'發車時間已過'])
	    			->withInput();
    	}

    	//判斷該區間是否還有座位
    	if($startStation->sequence < $endStation->sequence){
    		//南下列車
    		$currentTotalPassengers = DB::table('tickets')->where('train_number', $train->number)
    											->join('stations as start_station', 'tickets.start_station_id', '=', 'start_station.id')
    											->join('stations as end_station', 'tickets.end_station_id', '=', 'end_station.id')
    											->where('start_station.sequence', '>=', $startStation->sequence)
    											->where('end_station.sequence', '<=', $endStation->sequence)
    											->count();
    	}else{
    		//北上列車
    		$currentTotalPassengers = DB::table('tickets')->where('train_number', $train->number)
    											->join('stations as start_station', 'tickets.start_station_id', '=', 'start_station.id')
    											->join('stations as end_station', 'tickets.end_station_id', '=', 'end_station.id')
    											->where('start_station.sequence', '<=', $startStation->sequence)
    											->where('end_station.sequence', '>=', $endStation->sequence)
    											->count();
    	}
    	if(($currentTotalPassengers >= $train->passenger_total_number) || $request->numberOfTickets > ($train->passenger_total_number - $currentTotalPassengers)){
    		return redirect()->route('user.tickets.create')
	    			->withErrors(['numberOfTickets'=>'該區間已無足夠的空車位'])
	    			->withInput();
    	}

    	try{
	    	DB::beginTransaction();

	    	$ticket = new Ticket();
	    	$ticket->number = substr(md5(uniqid(rand(), true)),0,10);
	    	$ticket->cell_phone_number = $request->cellPhoneNumber;
	    	$ticket->start_station_id = $startStation->id;
	    	$ticket->end_station_id = $endStation->id;
	    	$ticket->boarding_date = $request->boardingDate;
	    	$ticket->train_number = $train->number;
	    	$ticket->number_of_tickets = $request->numberOfTickets;
	    	$ticket->save();

			DB::commit();
			Session::flash('success', '預訂車票成功');
			return redirect()->route('user.tickets.show', ['ticketNumber' => $ticket->number]);
	    } catch (Exception $e) {
			DB::rollback();
			Session::flash('error', '預訂車票失敗，請聯絡網站管理員');
			return redirect()->route('user.tickets.index');
		}
    }

    public function show($ticketNumber){
    	$ticket = Ticket::where('number', $ticketNumber)->firstOrfail();

    	return view('user.tickets.show', ['ticket' => $ticket]);
    }

    public function search(){
    	return view('user.tickets.search');
    }

    public function searchResult(Request $request){
    	$rules = [
    		"ticketNumber"=>"regex:/(^[A-z0-9]{10}$)/|nullable",
    		"cellPhoneNumber"=>"regex:/(^09[0-9]{2}-[0-9]{6}$)/|nullable",
    	];
    	$this->validate($request, $rules);
    	/*
    	$ticketsCount = Ticket::where('number', $request->ticketNumber)->orWhere('cell_phone_number', $request->cellPhoneNumber)->count();
    	if($ticketsCount <= 0){
    		return redirect()->route('user.tickets.search')
    						->withErrors(['ticket'=>'查無訂票紀錄'])
    						->withInput();
    	}*/

    	$tickets = Ticket::where('number', $request->ticketNumber)->orWhere('cell_phone_number', $request->cellPhoneNumber)->orderBy('created_at', 'asc')->paginate(10);
    	
    	//計算頁數
		if($tickets->lastPage() > 0){
    		//計算頁數
			if($tickets->lastPage() < $tickets->currentPage()){
				abort(404,'頁面不存在');
				exit;
			}
    	}
    	

    	return view('user.tickets.result', ['tickets' => $tickets, 'ticketNumber' => $request->ticketNumber, 'cellPhoneNumber' => $request->cellPhoneNumber]);
    }

    public function cancel($ticketNumber){
    	$ticket = Ticket::where('number', $ticketNumber)->firstOrfail();

    	if(strtotime($ticket->boarding_date." ".$ticket->train->route_infomation[$ticket->start_station_id]['departureTime']." -30min") <= time()){
    		Session::flash('error', '取消訂票失敗，列車出發前30分鐘內無法取消訂票');
    		return redirect()->route('user.tickets.show', ['ticketNumber' => $ticket->number]);
    	}

    	try{
    		DB::beginTransaction();

    		$ticket->is_cancel = true;
    		$ticket->canceled_at = date('Y-m-d H:i:s', time());
    		$ticket->save();

    		DB::commit();
			Session::flash('success', '取消訂票成功');
    	}catch(Exception $e){
    		DB::rollback();
			Session::flash('error', '取消訂票失敗，請聯絡網站管理員');
    	}
    	return redirect()->route('user.tickets.show', ['ticketNumber' => $ticket->number]);
    }

    public function adminSearch(){
    	$stations = Station::get();
    	return view("admin.tickets.search", ["stations" => $stations]);
    }

    public function adminSearchResult(Request $request){
    	$rules = [
    		'boardingDate'=>'date_format:Y-m-d|nullable',
    		'trainNumber'=>'numeric|exists:trains,number|nullable',
    		"cellPhoneNumber" => "regex:/(^09[0-9]{2}-[0-9]{6}$)/|nullable",
    		'startStation'=>'exists:stations,english_name|not_in:'.$request->endStation."|nullable",
	        'endStation'=>'exists:stations,english_name|not_in:'.$request->startStation."|nullable",
    	];
    	$this->validate($request, $rules);

    	/*
    	if($request->has('startStation')){
    		$startStation = Station::where("english_name", $request->startStation)->first();
    	}*/
    	$startStation = Station::where("english_name", $request->startStation)->first();
    	$endStation = Station::where("english_name", $request->endStation)->first();

    	($startStation) ? $startStationId = $startStation->id : $startStationId = "";
    	($endStation) ? $endStationId = $endStation->id : $endStationId = "";

resources/views/admin/tickets/result.blade.php
@extends('layouts.user')
@section('main-page')
<div class="row">

	<nav class="col-12">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item">管理後臺</li>
	    <li class="breadcrumb-item">訂票紀錄查詢</li>
	    <li class="breadcrumb-item active" aria-current="page">查詢結果</li>
	  </ol>
	</nav>	
</div>


<div class="row section-box">
	<div class="col-12">
		<table class="table text-center">
			<thead>
				<tr class="first-line">
					<th></th>
					<th>訂票編號</th>
					<th>訂票時間</th>
					<th>搭乘日期</th>
					<th>發車時間</th>
					<th>車次</th>
					<th>啟程站</th>
					<th>到達站</th>
					<th>訂購張數</th>
					<th></th>
			</thead>
			<tbody>
				@forelse($tickets as $ticket)
				<tr>
					<th>{{ ($tickets->currentPage()-1)*10+$loop->iteration }}</th>
					<td><a href="{{ route('user.tickets.show', ['ticketNumber' => $ticket->number]) }}" target="_blank">{{ $ticket->number }}</a></td>
					<td>{{ $ticket->created_at }}</td>
					<td>{{ $ticket->boarding_date }}</td>
					<td>{{ $ticket->train->route_infomation[$ticket->start_station_id]['departureTime'] }}</td>
					<td>{{ $ticket->train->number }}</td>
					<td>{{ $ticket->start_station->chinese_name }}</td>
					<td>{{ $ticket->end_station->chinese_name }}</td>
					<td>{{ $ticket->number_of_tickets }}</td>
					<td>
						@if($ticket->is_cancel)
							<p class="text-danger">已取消訂票<br>{{ $ticket->canceled_at }}</p>
						@elseif($ticket->is_delete)
							<p class="text-danger">已由網站管理員取消訂票<br>{{ $ticket->deleted_at }}</p>
						@elseif(strtotime($ticket->boarding_date." ".$ticket->train->route_infomation[$ticket->start_station_id]['departureTime']." -30min") > time())
							<form method="POST" action="{{ route('admin.tickets.cancel', ['ticketNumber' => $ticket->number]) }}">
								<input type="hidden" name="_token" value="{{ csrf_token() }}">
								<input type="hidden" name="_method" value="DELETE">
								<button type="submit" class="btn btn-danger" onclick="return confirm('確定要取消訂票嗎? 系統將無法復原您的動作')">取消訂票(管理員)</button>
							</form>
						@elseif(strtotime($ticket->boarding_date." ".$ticket->train->route_infomation[$ticket->start_station_id]['departureTime']) <= time())
							<p class="text-success">列車已出發</p>
						@endif
					</td>
				</tr>
				@empty
				<tr>
					<td colspan="10" class="text-secondary">查無訂票紀錄</td>
				</tr>
				@endforelse
			</tbody>
		</table>
	</div>
	<div class="col-12 d-flex justify-content-between">
		<a href="{{ route('admin.tickets.search') }}" class="btn btn-secondary">重新查詢</a>
		@if($tickets->lastPage() > 1)
        <nav>
          <ul class="pagination justify-content-end">
            @if( $tickets->currentPage() != 1 )
              <li class="page-item"><a class="page-link" href="{{ $tickets->url($tickets->currentPage()-1) }}"><</a></li>
            @endif
            @for($i = 1 ; $i <= $tickets->lastPage(); $i++)
              <li class="page-item {{ ($tickets->currentPage() == $i) ? 'active' : '' }}"><a class="page-link" href="{{ $tickets->url($i) }}">{{ $i }}</a></li>
            @endfor
            @if( $tickets->currentPage() != $tickets->lastPage() )
              <li class="page-item"><a class="page-link" href="{{ $tickets->nextPageUrl() }}">></a></li>
            @endif
          </ul>
        </nav>
      @endif
	</div>
</div>
@endsection

resources/views/admin/tickets/search.blade.php
@extends('layouts.admin')
@section('main-page')
<div class="row">
	<div class="col-12">
		<nav>
		  <ol class="breadcrumb">
		    <li class="breadcrumb-item">管理後臺</li>
		    <li class="breadcrumb-item active">訂票紀錄查詢</li>
		  </ol>
		</nav>
	</div>
</div>
@if(Session::has('success'))
<div class="row">
	<div class="alert alert-success col-12" role="alert">
	  {{Session::get('success')}}
	</div>
</div>
@elseif(Session::has('error'))
<div class="row">
	<div class="alert alert-danger col-12" role="alert">
	  {{Session::get('error')}}
	</div>
</div>
@endif
<div class="row section-box">
	<form id="form" class="col-12 offset-lg-3 col-lg-6" method="POST" action="{{ route('admin.tickets.search.result') }}">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<div class="form-group">
			<label><b>發車日期</b><a class="text-danger">*</a></label>
			<input type="date" name="boardingDate" class="form-control" value="{{ old('boardingDate') }}">
			@if($errors->has('boardingDate'))
				<label class="text-danger">{{ $errors->first('boardingDate') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>車次</b><a class="text-danger">*</a></label>
			<input type="number" name="trainNumber" class="form-control" value="{{ old('trainNumber')  }}">
			@if($errors->has('trainNumber'))
				<label class="text-danger">{{ $errors->first('trainNumber') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>手機號碼</b></label>
			<input type="text" name="cellPhoneNumber" class="form-control" value="{{ old('cellPhoneNumber')  }}">
			<label class="text-secondary">手機號碼格式範例：09XX-XXXXXX</label>
			@if($errors->has('cellPhoneNumber'))
				<br>
				<label class="text-danger">{{ $errors->first('cellPhoneNumber') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>訂票編號</b></label>
			<input type="text" name="ticketNumber" class="form-control" value="{{ old('ticketNumber')  }}">
			@if($errors->has('ticketNumber'))
				<label class="text-danger">{{ $errors->first('ticketNumber') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>啟程站</b><a class="text-danger">*</a></label>
			<select id="startStation" name="startStation" class="form-control">
				<option value="" selected>請選擇啟程站</option>
				@foreach($stations as $station)
					@if(old('startStation') == $station->english_name)
						<option data-value="{{ $station->sequence }}" value="{{$station->english_name}}" selected>{{ $station->chinese_name }}</option>
					@else
						<option data-value="{{ $station->sequence }}" value="{{$station->english_name}}">{{ $station->chinese_name }}</option>
					@endif
				@endforeach
			</select>
			@if($errors->has('startStation'))
				<label class="text-danger">{{ $errors->first('startStation') }}</label>
			@endif
	    </div>
	    <div class="form-group">
	    	<label><b>到達站</b><a class="text-danger">*</a></label>
			<select id="endStation" name="endStation" class="form-control">
				<option value="" selected>請選擇到達站</option>
	    		@foreach($stations as $station)
					@if(old('endStation') == $station->english_name)
						<option value="{{$station->english_name}}" selected>{{ $station->chinese_name }}</option>
					@else
						<option value="{{$station->english_name}}">{{ $station->chinese_name }}</option>
					@endif
				@endforeach
			</select>
			@if($errors->has('endStation'))
				<label class="text-danger">{{ $errors->first('endStation') }}</label>
			@endif
	    </div>
		<div class="form-group text-right">
			<button type="submit" class="btn btn-primary">查詢</button>
		</div>
	</form>
</div>
@endsection
@section('js-section')
<script type="text/javascript">

/* 發車站與終點站不重複 */
$("#startStation option[value='"+$("#endStation :selected").val()+"']").attr('disabled', true);
$("#endStation option[value='"+$("#startStation :selected").val()+"']").attr('disabled', true);
$('#startStation').on('change', function() {
	$("#endStation option").attr('disabled', false);
	if(this.value != ""){
		$("#endStation option[value='"+this.value+"']").attr('disabled', true);
	}
});
$('#endStation').on('change', function() {
	$("#startStation option").attr('disabled', false);
	if(this.value != ""){
		$("#startStation option[value='"+this.value+"']").attr('disabled', true);
	}
});
</script>
@endsection