routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('user.login.show');
Route::post('/login', 'Auth\LoginController@login')->name('user.login');

Route::group(['middleware' => 'auth'], function(){
});
*/
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login.show');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login');
Route::get('/admin/logout', 'Auth\AdminLoginController@logout')->name('admin.login.logout');

Route::get('/admin/types', 'TypeController@index')->name('admin.types.index');
Route::get('/admin/types/create', 'TypeController@create')->name('admin.types.create');
Route::post('/admin/types', 'TypeController@store')->name('admin.types.store');
Route::get('/admin/types/{id}/edit', 'TypeController@edit')->name('admin.types.edit');
Route::patch('/admin/types/{id}', 'TypeController@update')->name('admin.types.update');
Route::delete('/admin/types/{id}', 'TypeController@delete')->name('admin.types.delete');

Route::get('/admin/stations', 'StationController@index')->name('admin.stations.index');
Route::get('/admin/stations/create', 'StationController@create')->name('admin.stations.create');
Route::post('/admin/stations', 'StationController@store')->name('admin.stations.store');
Route::get('/admin/stations/{id}/edit', 'StationController@edit')->name('admin.stations.edit');
Route::patch('/admin/stations/{id}', 'StationController@update')->name('admin.stations.update');
Route::delete('/admin/stations/{id}', 'StationController@delete')->name('admin.stations.delete');

Route::get('/admin/trains', 'TrainController@index')->name('admin.trains.index');
Route::get('/admin/trains/create', 'TrainController@create')->name('admin.trains.create');
Route::post('/admin/trains/create/setStation', 'TrainController@setStation')->name('admin.trains.setStation');
Route::get('/admin/trains/create/route/{startStationEngName}/{endStationEngName}', 'TrainController@route')->name('admin.trains.route');
//Route::match(['get', 'post'], '/admin/trains/create/route', 'TrainController@route')->name('admin.trains.route');
Route::post('/admin/trains/create', 'TrainController@store')->name('admin.trains.store');
Route::get('/admin/trains/{train_number}/edit/info', 'TrainController@editInfo')->name('admin.trains.edit.info');
Route::patch('/admin/trains/{train_number}/edit/info', 'TrainController@updateInfo')->name('admin.trains.update.info');
Route::get('/admin/trains/{train_number}/edit/station', 'TrainController@editStation')->name('admin.trains.edit.station');
Route::post('/admin/trains/{train_number}/updateStation', 'TrainController@updateStation')->name('admin.trains.update.station');
Route::get('/admin/trains/{train_number}/edit/route/{startStationEngName}/{endStationEngName}', 'TrainController@editRoute')->name('admin.trains.edit.route');
Route::patch('/admin/trains/{train_number}/edit/route', 'TrainController@updateRoute')->name('admin.trains.update.route');
Route::delete('/admin/trains/{train_number}', 'TrainController@delete')->name('admin.trains.delete');

//Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/trains', 'TrainController@userIndex')->name('user.trains.index');
Route::get('/trains/{train_number}', 'TrainController@show')->where('train_number', '[0-9]+')->name('user.trains.show');
Route::get('/trains/search', 'TrainController@searchByNumber')->name('user.trains.search.by.number');
Route::post('/trains', 'TrainController@NumberSearchResult')->name('user.trains.number.search.result');
Route::get('/', 'TrainController@searchTrain')->name('user.trains.search');
Route::get('/trains/result/{boardingDate}/{startStationEngName}/{endStationEngName}/{type_id}', 'TrainController@TrainSearchResult')->name('user.trains.search.result');
//Route::match(['get', 'post'], '/tickets/create', 'TicketController')->name('tickets.create');

Route::get('/tickets', 'TicketController@index')->name('user.tickets.index');
//Route::get('/tickets/create', 'TicketController@create')->name('user.tickets.create');
Route::match(['get', 'post'], '/tickets/create', 'TicketController@create')->name('user.tickets.create');
Route::post('/tickets', 'TicketController@store')->name('user.tickets.store');
Route::get('/tickets/search', 'TicketController@search')->name('user.tickets.search');
Route::get('/tickets/{ticketNumber}', 'TicketController@show')->name('user.tickets.show');
Route::post('/tickets/search/result', 'TicketController@searchResult')->name('user.tickets.search.result');
Route::delete('/tickets/cancel/{ticketNumber}', 'TicketController@cancel')->name('user.tickets.cancel');

Route::get('/admin/tickets/search', 'TicketController@adminSearch')->name('admin.tickets.search');
Route::post('/admin/tickets/search/result', 'TicketController@adminSearchResult')->name('admin.tickets.search.result');
Route::delete('/admin/tickets/cancel/{ticketNumber}', 'TicketController@adminCancel')->name('admin.tickets.cancel');

app/Train.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Train extends Model
{

    //定義關聯
    //起始站
    function startStation(){
    	return $this->hasOne('App\Station', 'id', 'start_station_id');
    }
    //終點站
    function endStation(){
    	return $this->hasOne('App\Station', 'id', 'end_station_id');
    }
    //列車停靠資訊
    function routes(){
    	return $this->hasMany('App\Route', 'train_id', 'id')->orderBy('id', 'asc');
    }
    //列車車種
    function type(){
        return $this->hasOne('App\Type', 'id', 'type_id');
    }
    //行駛星期
    function drivingWeeks(){
        return $this->hasMany('App\DrivingWeek', 'train_id', 'id')->orderBy('week', 'asc');
    }
    //訂票紀錄
    function tickets(){
        return $this->hasMany('App\Ticket', 'train_number', 'number')->orderBy('created_at', 'asc');
    }

    //accessor
    public function getAllDrivingWeekChineseNameAttribute(){
        $drivingWeeks = $this->drivingWeeks;
        $arr_weeks = array();
        foreach ($drivingWeeks as $drivingWeek) {
            $arr_weeks[] = $drivingWeek->chinese_name;
        }
        return $arr_weeks;
    }

    public function getAllDrivingWeekNumberAttribute(){
        $drivingWeeks = $this->drivingWeeks;
        $arr_weeks = array();
        foreach ($drivingWeeks as $drivingWeek) {
            $arr_weeks[] = $drivingWeek->week;
        }
        return $arr_weeks;
    }

    //計算各站的預計到達時間、行駛時間及票價
    public function getRouteInfomationAttribute(){
            $departureTime = $this->departure_time;
            $routes = Route::where('train_id', $this->id)->get();
            $startRoute = Route::where('train_id', $this->id)->where('station_id', $this->start_station_id)->first();
            $endRoute = Route::where('train_id', $this->id)->where('station_id', $this->end_station_id)->first();

            $drivingMin = 0;
            $arr_routeInfo = [];
            foreach ($routes as $route) {
                //如果不是發車站就加上前站到此站的行駛時間
                if($route->id != $this->start_station_id){
                    $drivingMin += $route->driving_time;
                }

                //此站的預計到達時間
                $arrivalTime = date('H:i', strtotime($departureTime."+".$drivingMin."min"));

                //此站的行駛時間
                $dteStart = new \DateTime($departureTime);
                $dteEnd = new \DateTime($arrivalTime);
                $dteDiff = date('H:i', (strtotime($arrivalTime) - strtotime($departureTime)));

                //如果不是發車站或終點站就加上此站的停靠時間
                if($route->id != $this->start_station_id || $route->id != $this->end_station_id){
                    $drivingMin += $route->stay_time;
                    //此站的預計出發時間
                    $tmp_departureTime = date('H:i', strtotime($arrivalTime."+".$route->stay_time."min"));
                }else{
                    $tmp_departureTime = $arrivalTime;
                }

                $arr_routeInfo[$route->station_id] = [
                    'arrivalTime' => $arrivalTime,
                    'departureTime' => $tmp_departureTime,
                    'drivingTime' => $dteDiff,
                    'price' => $route->price
                ];
            }

            return $arr_routeInfo;
    }

    //取的兩站間的行駛時間
    public function getDrivingTimeBetweenTwoStation($startStation_id, $endStation_id){
        $departureTime = new \DateTime($this->route_infomation[$startStation_id]['departureTime']);
        $arrivalTime = new \DateTime($this->route_infomation[$endStation_id]['arrivalTime']);
        $timediff = $arrivalTime->diff($departureTime);
        $tmp_h = "";
        $tmp_i = "";
        if($timediff->h < 10){
           $tmp_h = "0";
        }
        if($timediff->i < 10){
           $tmp_i = "0";
        }
        return $timediff->format($tmp_h."%h:".$tmp_i."%i");
    }
}

resources/views/admin/trains/create.blade.php
@extends('layouts.admin')
@section('main-page')
<div class="row">
	<nav class="col-12">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="#">管理後臺</a></li>
	    <li class="breadcrumb-item"><a href="{{route('admin.trains.index')}}">列車管理</a></li>
	    <li class="breadcrumb-item active" aria-current="page">新增列車</li>
	  </ol>
	</nav>	
</div>

<div class="row mb-4">
	<div class="col-12 mb-1">
		<div class="row">
			<div class="col-6 text-center">
				Step 1. 發車、終點站設定
			</div>
			<div class="col-6 text-center">
				<p class="text-secondary">Step 2. 列車基本資訊與行經車站管理</p>
			</div>
		</div>
	</div>
	<div class="col-12">
		<div class="progress">
		  <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%"></div>
		</div>
	</div>
	
</div>
<div class="row section-box">
	<form class="col-12 offset-lg-3 col-lg-6" action="{{route('admin.trains.setStation')}}" method="POST">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<div class="form-group">
			<label><b>發車站</b><a class="text-danger">*</a></label>
			<select id="startStationfield" name="startStation" class="form-control">
			@foreach($stations as $station)
				@if(old('startStation') == $station->english_name)
					<option value="{{$station->english_name}}" selected>{{ $station->chinese_name }}</option>
				@else
					<option value="{{$station->english_name}}">{{ $station->chinese_name }}</option>
				@endif
			@endforeach
			</select>
			@if($errors->has('startStation'))
				<label class="text-danger">{{ $errors->first('startStation') }}</label>
			@endif
	    </div>
	    <div class="form-group">
	    	<label><b>終點站</b><a class="text-danger">*</a></label>
			<select id="endStationfield" name="endStation" class="form-control">
    		@foreach($stations as $station)
				@if(old('endStation') == $station->english_name)
					<option value="{{$station->english_name}}" selected>{{ $station->chinese_name }}</option>
				@elseif(old('endStation') === null && $loop->iteration == 2)
					<option value="{{$station->english_name}}" selected>{{ $station->chinese_name }}</option>
				@else
					<option value="{{$station->english_name}}">{{ $station->chinese_name }}</option>
				@endif
			@endforeach
			</select>
			@if($errors->has('endStation'))
				<label class="text-danger">{{ $errors->first('endStation') }}</label>
			@endif
	    </div>
		<div class="form-group text-right">
			<input type="submit" class="btn btn-info" value="下一步">
		</div>
	</form>
</div>
@endsection
@section('js-section')
<script type="text/javascript">
/* 離開頁面前的檢查 */
$(window).bind('beforeunload', function (e) {
    return '資料尚未存檔，確定是否要離開?';
    
})
$("input:submit").click(function () {
    $(window).unbind('beforeunload');
});

/* 發車站與終點站不重複 */
$("#startStationfield option[value='"+$("#endStationfield :selected").attr('value')+"']").attr('disabled', true);
$("#endStationfield option[value='"+$("#startStationfield :selected").attr('value')+"']").attr('disabled', true);
$('#startStationfield').on('change', function() {
	$("#endStationfield option").attr('disabled', false);
	$("#endStationfield option[value='"+this.value+"']").attr('disabled', true);
});
$('#endStationfield').on('change', function() {
	$("#startStationfield option").attr('disabled', false);
	$("#startStationfield option[value='"+this.value+"']").attr('disabled', true);
});

</script>
@endsection

resources/views/admin/trains/editInfo.blade.php
@extends('layouts.admin')
@section('main-page')
<div class="row">
	<nav class="col-12">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="#">管理後臺</a></li>
	    <li class="breadcrumb-item"><a href="{{route('admin.trains.index')}}">列車管理</a></li>
	    <li class="breadcrumb-item">{{ $train->number }}</li>
	    <li class="breadcrumb-item active" aria-current="page">修改列車基本資訊</li>
	  </ol>
	</nav>	
</div>

<div class="row section-box">
	<form class="col-12 offset-lg-3 col-lg-6" action="{{route('admin.trains.update.info', ['number' => $train->number])}}" method="POST">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		{{ method_field('PATCH') }}
		<div class="form-group">
			<label><b>列車代碼</b></label>
			<input type="number" name="number" class="form-control" value="{{ (old('number')) ? old('number') : $train->number }}">
			@if($errors->has('number'))
				<label class="text-danger">{{ $errors->first('number') }}</label>
			@endif
		</div>
	    <div class="form-group">
	    	<label><b>請選擇車種</b><a class="text-danger">*</a></label>
	    	<select name="type" class="form-control">
	    	@foreach($types as $type)
	    		<option value="{{$type->id}}" {{ (old('type')) ? (old('type') == $type->id) ? 'selected' : '' : ($train->type->id == $type->id) ? 'selected' : '' }}>{{$type->type_name}}</option>
	    	@endforeach
	    	</select>
		</div>
		<div class="form-group">
			<label><b>單一車廂的載客數量</b><a class="text-danger">*</a></label>
			<input type="number" id="passengerNumber" name="passengerNumber" class="form-control" value="{{ (old('passengerNumber')) ? old('passengerNumber') : $train->passenger_number }}">
			@if($errors->has('passengerNumber'))
				<label class="text-danger">{{ $errors->first('passengerNumber') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>車廂數量</b><a class="text-danger">*</a></label>
			<input type="number" id="cabinNumber" name="cabinNumber" class="form-control" value="{{ (old('cabinNumber')) ? old('cabinNumber') : $train->cabin_number }}">
			@if($errors->has('cabinNumber'))
				<label class="text-danger">{{ $errors->first('cabinNumber') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>總載客數</b></label>
			<input type="number" id="passengerTotalNumber" name="passengerTotalNumber" class="form-control" value="{{ (old('passengerTotalNumber')) ? old('passengerTotalNumber') : $train->passenger_total_number }}" readonly="true">
		</div>
		<div class="form-group">
			<label><b>行車星期</b><a class="text-danger">*</a></label>
			@foreach($arr_weeks as $week)
			<div class="form-check">
				<input name="drivingWeeks[]" class="form-check-input" type="checkbox" value="{{$loop->iteration}}" id="checkbox-{{$loop->iteration}}" {{ $arr_drivingWeeks[$loop->index] }}>
				<label class="form-check-label" for="checkbox-{{$loop->iteration}}">
					{{ $week }}
				</label>
			</div>
			@endforeach
			@if($errors->has('drivingWeeks'))
				<label class="text-danger">{{ $errors->first('drivingWeeks') }}</label>
			@endif
		</div>
		<div class="form-group">
			<label><b>發車時間</b><a class="text-danger">*</a></label>
			<input type="time" name="departureTime" class="form-control" value="{{ (old('departureTime')) ? date('H:i', strtotime(old('departureTime'))) : date('H:i', strtotime($train->departure_time)) }}">
			@if($errors->has('departureTime'))
				<label class="text-danger">{{ $errors->first('departureTime') }}</label>
			@endif
		</div>
		<div class="form-group text-right">
			<a href="{{ route('admin.trains.index') }}" onclick="return confirm('確定要取消修改這次的動作嗎? 系統將無法復原您的資料')" class="btn btn-secondary">取消</a>
			<input type="submit" class="btn btn-primary" value="送出">
		</div>
	</form>
</div>
@endsection
@section('js-section')
<script type="text/javascript">
/* 離開頁面前的檢查 */
$(window).bind('beforeunload', function (e) {
    return '資料尚未存檔，確定是否要離開?';
    
})
$("input:submit").click(function () {
    $(window).unbind('beforeunload');
});


function count(){
	total = parseInt($("#passengerNumber").val()) * parseInt($("#cabinNumber").val());
	$($("#passengerTotalNumber").val(total));
}

$("#passengerNumber").on('change', function() {
	count();
});
$("#cabinNumber").on('change', function() {
	count();
});

order();
</script>
@endsection

resources/views/admin/trains/editRoute.blade.php
@extends('layouts.admin')
@section('main-page')
<div class="row">
	<nav class="col-12">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="#">管理後臺</a></li>
	    <li class="breadcrumb-item"><a href="{{route('admin.trains.index')}}">列車管理</a></li>
	    <li class="breadcrumb-item">{{ $train->number }}</li>
	    <li class="breadcrumb-item active" aria-current="page">修改列車停靠、停駛車站</li>
	  </ol>
	</nav>	
</div>

<div class="row mb-4">
	<div class="col-12 mb-1">
		<div class="row">
			<div class="col-6 text-center">
				<p class="text-secondary">Step 1. 發車、終點站設定</p>
			</div>
			<div class="col-6 text-center">
				Step 2. 列車行經車站管理
			</div>
		</div>
	</div>
	<div class="col-12">
		<div class="progress">
		  <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 100%"></div>
		</div>
	</div>
	
</div>
<div class="row section-box">
	<form class="col-12 offset-lg-3 col-lg-6" action="{{ route('admin.trains.update.route', ['train_number' => $train->number]) }}" method="POST">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		{{ method_field('PATCH') }}
		<div class="row text-center mb-5">
			<div class="col-4">
				<h3>{{ $startStation->chinese_name }}</h3>
			</div>
			<div class="col-4">
				<img width="48" height="48" src="{{ asset('images/right-arrow.png') }}">
			</div>
			<div class="col-4">
				<h3>{{ $endStation->chinese_name }}</h3>
			</div>
		</div>
		<hr>
	    <div class="form-group">
	    	@foreach($stations as $station)
	    	<div class="form-row">
			    <div class="col-md-12">
			      <label>#{{ $loop->iteration }} <b>{{ $station->chinese_name }} {{ $loop->iteration == 1 ? '(發車站)' : '' }}{{ $loop->iteration == count($stations) ? '(終點站)' : '' }}</b></label>
			      @if($errors->has('stayTime.'.$loop->index) || $errors->has('drivingTime.'.$loop->index) || $errors->has('price.'.$loop->index))
			      	<label class="text-danger">該車站停留時間、行駛時間或是票價設定錯誤</label>
			      @endif
			      <input type="hidden" name="station[]" value="{{ $station->id }}">
			    </div>
			    <div class="form-group col-12 col-lg-4">
			      <label>停留時間(min)<a class="text-danger">*</a></label>
			      <input type="number" name="stayTime[]" class="form-control plus-time" min="0" value="{{ $arr_stayTimeValue[$loop->index] }}" {{ $loop->iteration == 1 || $loop->iteration == count($stations) ? 'readonly="true"' : '' }}>
			    </div>
			    <div class="form-group col-12 col-lg-5">
			      <label>前站到此的行駛時間(min)<a class="text-danger">*</a></label>
			      <input type="number" name="drivingTime[]" class="form-control plus-time" min="0" value="{{ $arr_drivingTimeValue[$loop->index] }}" {{ $loop->iteration == 1 ? 'readonly="true"' : '' }}>
			    </div>
			    <div class="form-group col-12 col-lg-3">
			      <label>票價<a class="text-danger">*</a></label>
			      <input type="number" name="price[]" class="form-control" min="0" value="{{ $arr_priceValue[$loop->index] }}" {{ $loop->iteration == 1 ? 'readonly="true"' : '' }}>
			    </div>
			</div>
			@endforeach
	    </div>
	    <div class="row">
	    <div class="form-group col-6">
			<a id="back-info" class="btn btn-secondary" href="{{ route('admin.trains.edit.station',['train_number'=>$train->number]) }}">上一步</a>
		</div>
		<div class="form-group col-6 text-right">
			<input type="submit" class="btn btn-primary" value="送出">
		</div>
		</div>
	</form>
</div>
@endsection
@section('js-section')
<script type="text/javascript">


/* 離開頁面前的檢查 */
$(window).bind('beforeunload', function (e) {
    return '資料尚未存檔，確定是否要離開?';
    
})
$("input:submit").click(function () {
    $(window).unbind('beforeunload');
});
$("#back-info").click(function () {
    $(window).unbind('beforeunload');
});

/* 計算最終抵達時間 */
/*
$('.plus-time').on('change', function() {
	var count = 0;
	$(".plus-time").each(function() {
	    //console.log($(this).val());
	    if(parseInt($(this).val()) > 0){
	    	count += parseInt($(this).val());
	    }
	    //count = parseInt($(this).val());
	});
	//console.log(count);
	var date = add_minutes(new Date('1997-12-15 '+$("#startTime").val()), count);
	var year = date.getFullYear().toString();
	var mouth = (date.getMonth() + 1);

	//月份補0
	if(mouth < 10){
		mouth = "0"+mouth.toString();
	}else{
		mouth = mouth.toString();
	}
	var day = date.getDate().toString();
	var hours = date.getHours();

	//小時補0
	if(hours < 10){
		hours = "0"+hours.toString();
	}else{
		hours = hours.toString();
	}

	//分鐘補0
	var minutes = date.getMinutes().toString();
	if(minutes.length < 2){
		minutes = "0"+minutes;
	}
	//console.log(date+"/"+year+"/"+mouth+"/"+day+" "+hours+":"+minutes);
	var time = hours+":"+minutes;
	$("#endTime").val(time);
});

function add_minutes(dt, minutes) {
	return new Date(dt.getTime() + minutes*60000);
}
*/
$("#passengerNumber").on('change', function() {
	count();
});

$("#cabinNumber").on('change', function() {
	count();
});

function count(){
	total = parseInt($("#passengerNumber").val()) * parseInt($("#cabinNumber").val());
	$($("#passengerTotalNumber").val(total));
}

</script>
@endsection

resources/views/admin/trains/index.blade.php
@extends('layouts.admin')
@section('main-page')
<div class="row">
	<nav class="col-8 col-md-6">
	  <ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="#">管理後臺</a></li>
		<li class="breadcrumb-item active" aria-current="page">列車管理</li>
	  </ol>
	</nav>
	<div class="col-4 col-md-6 text-right pt-2">
		<a href="#" class="btn btn-info">查詢列車資訊</a>
		<a href="{{route('admin.trains.create')}}" class="btn btn-primary">新增列車</a>	
	</div>
	@if (Session::has('success'))
	<div class="alert alert-success col-12" role="alert">
	  {{Session::get('success')}}
	</div>
	@endif
	@if (Session::has('error'))
	<div class="alert alert-danger col-12" role="alert">
	  {{Session::get('error')}}
	</div>
	@endif
</div>


<div class="row section-box">
	<div class="col-12">
		<table class="table text-center">
			<thead>
				<tr class="first-line">
					<th></th>
					<th>車種</th>
					<th>列車編號</th>
					<th>發車站</th>
					<th>終點站</th>
					<th>預計開車時間</th>
					<th>預計到達時間</th>
					<th>行駛時間</th>
					<th>行車星期</th>
					<th></th>
			</thead>
			<tbody>
				@forelse($trains as $train)
				<tr>
					<th>{{ ($trains->currentPage()-1)*10+$loop->iteration }}</th>
					<td>{{ $train->type->type_name }}</td>
					<td><a href="{{ route('user.trains.show', ['train_number' => $train->number]) }}" target="_blank">{{ $train->number }}</a></td>
					<td>{{ $train->startStation->chinese_name }}</td>
					<td>{{ $train->endStation->chinese_name }}</td>
					<td>{{ date('H:i', strtotime($train->departure_time)) }}</td>
					<td>{{ $train->route_infomation[$train->end_station_id]['arrivalTime'] }}</td>
					<td>{{ $train->route_infomation[$train->end_station_id]['drivingTime'] }}</td>
					<td>{{ implode('、', $train->all_driving_week_chinese_name) }}</td>
					<td>
						<div class="dropdown show">
							<a class="dropdown-toggle" href="#" data-toggle="dropdown">
							</a>

							<div class="dropdown-menu">
								<a class="dropdown-item" href="{{ route('admin.trains.edit.info',['train_number'=>$train->number]) }}">修改基本資訊</a>
								<a class="dropdown-item" href="{{ route('admin.trains.edit.station',['train_number'=>$train->number]) }}">修改停靠、停駛車站</a>
								<form method="POST" action="{{ route('admin.trains.delete',['number'=>$train->number]) }}">
									{{ method_field('DELETE') }}
									<input type="hidden" name="_token" value="{{ csrf_token() }}">
									<button type="submit" class="dropdown-item text-danger" onclick="return confirm('確定要刪除嗎? 系統將無法復原您的動作')">刪除</button>
								</form>
							</div>
						</div>
					</td>
				</tr>
				@empty
				<tr>
					<td colspan="10" class="text-secondary">查無指定條件車次</td>
				</tr>
				@endforelse
			</tbody>
		</table>
	</div>
	@if($trains->lastPage() > 1)
		<div class="col-12">
	        <nav>
	          <ul class="pagination justify-content-end">
	            @if( $trains->currentPage() != 1 )
	              <li class="page-item"><a class="page-link" href="{{ $trains->url($trains->currentPage()-1) }}"><</a></li>
	            @endif
	            @for($i = 1 ; $i <= $trains->lastPage(); $i++)
	              <li class="page-item {{ ($trains->currentPage() == $i) ? 'active' : '' }}"><a class="page-link" href="{{ $trains->url($i) }}">{{ $i }}</a></li>
	            @endfor
	            @if( $trains->currentPage() != $trains->lastPage() )
	              <li class="page-item"><a class="page-link" href="{{ $trains->nextPageUrl() }}">></a></li>
	            @endif
	          </ul>
	        </nav>
	    </div>
    @endif
</div>
@endsection